<?php

if (!defined('BASEPATH'))
  exit('No direct script access allowed');

class Ruang extends CI_Controller
{
  function __construct()
  {
    parent::__construct();
    check_not_login();
    check_admin();
    $this->load->model('Ruang_model');
    $this->load->library('form_validation');
    $this->load->library('datatables');
  }

  public function index()
  {
    $data = array(
      'title' => " Data Ruang"
    );
    $this->load->view('ruang/ruang_data', $data);
  }

  public function json()
  {
    header('Content-Type: application/json');
    echo $this->Ruang_model->json();
  }

  public function read($id)
  {
    $row = $this->Ruang_model->get_by_id($id);
    if ($row) {
      $data = array(
        'id' => $row->id,
        'nama_ruang' => $row->nama_ruang,
      );
      $this->load->view('ruang/tb_ruang_read', $data);
    } else {
      $this->session->set_flashdata('message', 'Record Not Found');
      redirect(site_url('Ruang'));
    }
  }

  public function create()
  {
    $data = array(
      'button' => 'Create',
      'action' => site_url('Ruang/create_action'),
      'id' => set_value('id'),
      'nama_ruang' => set_value('nama_ruang'),
    );
    $this->load->view('ruang/tb_ruang_form', $data);
  }

  public function create_action()
  {
    $this->_rules();

    if ($this->form_validation->run() == FALSE) {
      $this->create();
    } else {
      $data = array(
        'nama_ruang' => $this->input->post('nama_ruang', TRUE),
      );

      $this->Ruang_model->insert($data);
      $this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible show fade">
            <div class="alert-body">
              <button class="close" data-dismiss="alert">
                <span>&times;</span>
              </button>
              Berhasil menambah data!
            </div>
          </div>');
      redirect(site_url('Ruang'));
    }
  }

  public function update($id)
  {
    $row = $this->Ruang_model->get_by_id($id);

    if ($row) {
      $data = array(
        'title' => 'Ruang',
        'page' => 'Update Ruang',
        'button' => 'Update',
        'action' => site_url('Ruang/update_action'),
        'id' => set_value('id', $row->id),
        'nama_ruang' => set_value('nama_ruang', $row->nama_ruang),
      );
      $this->load->view('ruang/ruang_edit', $data);
    } else {
      $this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible show fade">
            <div class="alert-body">
              <button class="close" data-dismiss="alert">
                <span>&times;</span>
              </button>
              Data tidak ditemukan!
            </div>
          </div>');
      redirect(site_url('Ruang'));
    }
  }

  public function update_action()
  {
    $this->_rules();

    if ($this->form_validation->run() == FALSE) {
      $this->update($this->input->post('id', TRUE));
    } else {
      $data = array(
        'nama_ruang' => $this->input->post('nama_ruang', TRUE),
      );

      $this->Ruang_model->update($this->input->post('id', TRUE), $data);
      $this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible show fade">
            <div class="alert-body">
              <button class="close" data-dismiss="alert">
                <span>&times;</span>
              </button>
              Berhasil memperbarui data!
            </div>
          </div>');
      redirect(site_url('Ruang'));
    }
  }

  public function delete($id)
  {
    $row = $this->Ruang_model->get_by_id($id);

    if ($row) {
      $this->Ruang_model->delete($id);
      $this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible show fade">
            <div class="alert-body">
              <button class="close" data-dismiss="alert">
                <span>&times;</span>
              </button>
              Berhasil menghapus data!
            </div>
          </div>');
      redirect(site_url('Ruang'));
    } else {
      $this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible show fade">
            <div class="alert-body">
              <button class="close" data-dismiss="alert">
                <span>&times;</span>
              </button>
              Data tidak ditemukan!
            </div>
          </div>');
      redirect(site_url('Ruang'));
    }
  }

  public function _rules()
  {
    $this->form_validation->set_rules('nama_ruang', 'nama ruang', 'trim|required');
  }
}

/* End of file Ruang.php */
/* Location: ./application/controllers/Ruang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-13 05:31:40 */
/* http://harviacode.com */
