<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Satuan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        check_not_login();
        check_admin();
        $this->load->model('Satuan_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        $data = array(
            'title' => "Data Satuan"
        );
        $this->load->view('satuan/satuan_data', $data);
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Satuan_model->json();
    }

    public function read($id)
    {
        $row = $this->Satuan_model->get_by_id($id);
        if ($row) {
            $data = array(
                'id' => $row->id,
                'satuan' => $row->satuan,
            );
            $this->load->view('satuan/tb_satuan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('Satuan'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('Satuan/create_action'),
            'id' => set_value('id'),
            'satuan' => set_value('satuan'),
        );
        $this->load->view('satuan/satuan_data', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'satuan' => $this->input->post('_satuan', TRUE),
            );

            $this->Satuan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('Satuan'));
        }
    }

    public function update($id)
    {
        $row = $this->Satuan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'title' => 'Satuan',
                'page' => 'Update Satuan',
                'button' => 'Update',
                'action' => site_url('Satuan/update_action'),
                'id' => set_value('id', $row->id),
                'satuan' => set_value('satuan', $row->satuan),
            );
            // $this->load->view('satuan/tb_satuan_form', $data);
            $this->load->view('satuan/satuan_edit', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('Satuan'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'satuan' => $this->input->post('_satuan', TRUE),
            );

            $this->Satuan_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('Satuan'));
        }
    }

    public function delete($id)
    {
        $row = $this->Satuan_model->get_by_id($id);

        if ($row) {
            $this->Satuan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('Satuan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('Satuan'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('_satuan', 'satuan', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Satuan.php */
/* Location: ./application/controllers/Satuan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-11 04:08:32 */
/* http://harviacode.com */
