<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Stok_model extends CI_Model
{

    public $table = 'tb_stok';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($session = null)
    {
        $this->datatables->select('s.id,s.kode_barang,s.stok,r.nama_ruang as ruang');
        $this->datatables->from('tb_stok as s');
        //add this line for join
        $this->datatables->join('tb_ruang as r', 's.id_ruang = r.id');
        if ($session != null) {
            $this->datatables->where('s.id_ruang', $session);
        }
        // $this->datatables->add_column('action', anchor(site_url('stok/read/$1'),'Read')." | ".anchor(site_url('stok/update/$1'),'Update')." | ".anchor(site_url('stok/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('kode_barang', $q);
        $this->db->or_like('stok', $q);
        $this->db->or_like('id_ruang', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('kode_barang', $q);
        $this->db->or_like('stok', $q);
        $this->db->or_like('id_ruang', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Stok_model.php */
/* Location: ./application/models/Stok_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-06 03:21:36 */
/* http://harviacode.com */